### ISSUE TITLE
Empty strings and unknown values should be treated as null properties and not included for the items where they are null

### ISSUE THREAD

**Issue by nickevansuk** [openactive/developer-microsite#10]
## Rule name
Empty strings and unknown values should be treated as null properties and not included for the items where they are null

## Rule type
Validation warning

## Rule hint
Empty strings should always be returned as null and therefore not included in the output by a JSON serialiser

## Associated proposal or model reference
- https://github.com/openactive/modelling-opportunity-data/issues/91

## Examples
- https://github.com/openactive/activation/issues/119

**Comment by drchristhorpe** [comment]
Already done

https://github.com/openactive/developer-microsite/blob/e87c6dfa46a0674d756518662f478e452cf6b97b/app/feed_tools/checker.py#L283
