### ISSUE TITLE
givenName should not be two words, if no familyName is provided consistently, and vice versa. "name" should be used instead to represent full name.

### ISSUE THREAD

**Issue by nickevansuk** [openactive/developer-microsite#11]
## Rule name
givenName should not be two words, if no familyName is provided consistently, and vice versa. "name" should be used instead to represent full name

## Rule type
Data quality warning

## Rule hint
Ensure that givenName, familyName, and name are being used correctly. "name" should be used instead to represent full name.

## Examples
- https://github.com/openactive/activation/issues/120

**Comment by ldodds** [comment]
There are cases where this won't be true. Names are tricky

I'd prefer keeping to what is in the specification and just recommend use of the name property
