### ISSUE TITLE
If providing a programme, always try to include a logo, a url and a video

### ISSUE THREAD

**Issue by nickevansuk** [openactive/developer-microsite#14]
## Rule name
If providing a programme, always try to include a logo, a url and a video

## Rule type
Data quality warning

## Rule hint
A logo, URL and a video will help end-users to understand what they can expect from the programme.

## Associated proposal or model reference
- https://github.com/openactive/modelling-opportunity-data/issues/88
- https://github.com/openactive/modelling-opportunity-data/issues/89

## Examples
- https://github.com/openactive/activation/issues/121
- https://github.com/openactive/activation/issues/155

**Comment by ldodds** [comment]
Am closing this as a validation requirement until we've decided on how to better handle programmes. Otherwise we aren't giving consistent advice.

Adding these extra properties may be useful but validator should ignore for now
