### ISSUE TITLE
URL property is mandatory when describing an event

### ISSUE THREAD

**Issue by nickevansuk** [openactive/developer-microsite#22]
## Rule name
URL property is mandatory when describing an event

## Rule type
Validation error

## Rule hint
Thus URL must be available as a means for providing users with a link to more information about the event.

## Associated proposal or model reference
- https://www.openactive.io/modelling-opportunity-data/#describing-events-code-schema-event-code-

## Examples
- https://github.com/openactive/activation/issues/131

**Comment by drchristhorpe** [comment]
It's already a required field

"requiredFields": ["context","activity","location","name","url"],

https://github.com/openactive/developer-microsite/blob/e87c6dfa46a0674d756518662f478e452cf6b97b/app/models/Event.json#L9
