### ISSUE TITLE
Event should include "duration" property

### ISSUE THREAD

**Issue by nickevansuk** [openactive/developer-microsite#23]
## Rule name
Event should include `"duration"` property

## Rule type
Data quality warning

## Rule hint
The difference between startTime and endTime e.g. "PT60M". This should be included for data users to display the correct duration in their UIs. Note must be converted to ISO spec. This can be done with System.Xml.XmlConvert.ToString(TimeSpan.FromMinutes(duration))

## Examples
- https://github.com/openactive/activation/issues/132

**Comment by drchristhorpe** [comment]
It is a required field in the Event model


"recommendedFields": ["description","duration","organizer","eventStatus"],

https://github.com/openactive/developer-microsite/blob/e87c6dfa46a0674d756518662f478e452cf6b97b/app/models/Event.json#L14

and is defined as an ISO8601 duration (we need to implement the checking rule for this)

https://github.com/openactive/developer-microsite/blob/e87c6dfa46a0674d756518662f478e452cf6b97b/app/models/Event.json#L86

**Comment by ldodds** [comment]
This is already a recommended field.
