### ISSUE TITLE
Boolean values should be boolean

### ISSUE THREAD

**Issue by nickevansuk** [openactive/developer-microsite#29]
## Rule name
Boolean values should be boolean

## Rule type
Validation error

## Rule hint
Ensure that all boolean are represented as a JSON native boolean type.

## Associated proposal or model reference
- https://www.openactive.io/modelling-opportunity-data/EditorsDraft/#describing-amenities

## Examples
- https://github.com/openactive/activation/issues/138

**Comment by ldodds** [comment]
+1 have updated the proposal to note this, am also identifying the relevant properties
