### ISSUE TITLE
GeoCoordinates must be specified as decimal values

### ISSUE THREAD

**Issue by nickevansuk** [openactive/developer-microsite#30]
## Rule name
GeoCoordinates must be specified as decimal values

## Rule type
Validation error

## Rule hint
As well as being expected by data users, GeoCoordinates are only recongnised by the status dashboard as being present if they are specified as decimal.

## Associated proposal or model reference
- https://github.com/openactive/modelling-opportunity-data/issues/99

## Examples
- https://github.com/openactive/activation/issues/139
- https://github.com/openactive/activation/issues/149

**Comment by ldodds** [comment]
+1 this is what we are proposing for 2.0
