### ISSUE TITLE
genderRestriction should always use one of the enum values, instead of any variation of male, female or mixed

### ISSUE THREAD

**Issue by nickevansuk** [openactive/developer-microsite#33]
## Rule name
genderRestriction should always use one of the enum values, instead of any variation of `male`, `female` or `mixed`/`none`

## Rule type
Validation warning

## Rule hint
In order to maximise usefulness of this field for data users, `male`, `female` and `mixed` options should use the enum values provided in the specification.

Enum values as follows:
- `"http://openactive.io/ns#None"`
- `"http://openactive.io/ns#Female"`
- `"http://openactive.io/ns#Male"`

## Associated proposal or model reference
- https://github.com/openactive/modelling-opportunity-data/issues/69

## Examples
- https://github.com/openactive/activation/issues/142
- https://github.com/openactive/activation/issues/147

**Comment by ldodds** [comment]
Just noting this is an error rather than a warning. Closing as this is covered by the specificstion
