### ISSUE TITLE
The "amenityFeature" property should be inside the "location" object

### ISSUE THREAD

**Issue by nickevansuk** [openactive/developer-microsite#36]
## Rule name
The "amenityFeature" property should be inside the "location" object

## Rule type
Validation error

## Rule hint
amenityFeature is a property of the Place where an activity takes place, not a property of the event itself

## Associated proposal or model reference
- https://www.openactive.io/modelling-opportunity-data/EditorsDraft/#describing-amenities

## Examples
- https://github.com/openactive/activation/issues/146

**Comment by ldodds** [comment]
This will be caught by the core validation rules that check how the amenity feature property is applied.
