### ISSUE TITLE
Integers should be represented as number

### ISSUE THREAD

**Issue by nickevansuk** [openactive/developer-microsite#37]
## Rule name
Integers should be represented as numbers

## Rule type
Validation warning

## Rule hint
This property, although not defined in the schema, appears to be describing an integer. Integers should be described as JSON numbers, and not strings.

## Rule notes
Note this should be applied to any unknown property in the schema (assumed to be a custom property), in order to maximise the usefulness of such properties.

## Examples
- https://github.com/openactive/activation/issues/151
- https://github.com/openactive/activation/issues/152

**Comment by ldodds** [comment]
The imoroved validation proposal I'm the modelling spec already covers this, so am closing here.

However I don't think we should assume any unknown property is an integer, or attempt to guess whether it should be. The rule will be to warn and ignore unknown properties.
