### ISSUE TITLE
"addressRegion" must be a string

### ISSUE THREAD

**Issue by nickevansuk** [openactive/developer-microsite#6]
## Rule name
"addressRegion" must be a string

## Rule type
Validation error

## Rule hint
Objects may only be used for properties that allow them.

## Examples
- https://github.com/openactive/activation/issues/117

**Comment by drchristhorpe** [comment]
Is a text field in the PostalAddress model

https://github.com/openactive/developer-microsite/blob/e87c6dfa46a0674d756518662f478e452cf6b97b/app/models/PostalAddress.json#L24
