### ISSUE TITLE
"addressCountry" must always be provided

### ISSUE THREAD

**Issue by nickevansuk** [openactive/developer-microsite#8]
## Rule name
"addressCountry" must always be provided

## Rule type
Validation error

## Rule hint
Suggest "GB" as a default value for UK based providers

## Associated proposal
- https://github.com/openactive/modelling-opportunity-data/issues/90

## Examples
- https://github.com/openactive/activation/issues/117
- https://github.com/openactive/activation/issues/148

**Comment by drchristhorpe** [comment]
It's already a required field
"requiredFields": ["addressCountry", "streetAddress", "postalCode"],

https://github.com/openactive/developer-microsite/blob/13eabcb078f2eff8cdae027f4c12243359908071/app/models/PostalAddress.json#L6
