### ISSUE TITLE
null properties or objects that contain only null values should not be included

### ISSUE THREAD

**Issue by nickevansuk** [openactive/developer-microsite#9]
## Rule name
null properties or objects that contain only null values should not be included.

## Rule type
Validation warning

## Rule hint
Not including null properties reduces the size of feeds

## Associated proposal or model reference
- https://github.com/openactive/modelling-opportunity-data/issues/91

## Examples
- https://github.com/openactive/activation/issues/118

**Comment by drchristhorpe** [comment]
Already done

https://github.com/openactive/developer-microsite/blob/e87c6dfa46a0674d756518662f478e452cf6b97b/app/feed_tools/checker.py#L283
